### ISSUE TITLE
0.93b1 not using plugins/ram directory

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#10]
The ram data files are now being created  in the plugins\RedstoneChips  directory instead of  plugins\RedstoneChips\sram

The sram directory is not being created either

(Win Xp sp2   :version 3:01:58 [INFO] This server is running Craftbukkit version git-Bukkit-1.0.1-R1-b
597jnks (MC: 1.0.1) (Implementing API version 1.0.1-R1)

**Comment by eisental** [comment]
Could you double check? I just tried a clean installation and everything
worked as expected. Did you update BasicCircuits as well as RedstoneChips?

On Fri, Dec 30, 2011 at 6:57 PM, Mike Stramba <
reply@reply.github.com

**Comment by mstram** [comment]
I just rebooted my machine, still the same (though the ram chip _is_
working (so the directory thing is not a big deal .... other than it's
not working as expected  ... or that it seemingly is not working the
same on my xp box as your Mac ;)

> rc
> 13:41:35 [INFO] ---- RedstoneChips 0.93b1 ------------------------------
> 13:41:35 [INFO] For more info see: http://eisental.github.com/RedstoneChips
> 13:41:35 [INFO] Type /rchelp for a list of all RedstoneChips commands.
> 13:41:35 [INFO] Installed circuit libraries:
> 13:41:35 [INFO]  - SensorLibrary 0.31b0
> 13:41:35 [INFO]  - BasicCircuits 0.93b1
> 13:41:35 [INFO] ----------------------

On 12/30/11, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by eisental** [comment]
Your plugin version is an old test release (0.93b1)...
