### ISSUE TITLE
req -shift right register

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#13]
It would be great to have both a left (which BC currently does have)  and right shifting register

Maybe add an optional left / right parameter on the shiftregister sign ?

Mike

**Comment by eisental** [comment]
Done, added left/right argument.

**Comment by mstram** [comment]
Great .. can you upload the jar(s) ?

On 1/9/12, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by eisental** [comment]
ehm, I uploaded yesterday...
