### ISSUE TITLE
While saveing to sram on adres x the output is seted on adress y

### ISSUE THREAD

**Issue by Kubuxu** [eisental/BasicCircuits#20]
Like in title.

**Comment by jpfx1342** [comment]
Could you provide more details about your set up? What are addresses X and Y? When you say save, do you mean toggling the write pin?

Any details are helpful. If you can't provide details, a (small-ish) world save or multiplayer server link would be appreciated as well.

**Comment by Kubuxu** [comment]
I have input registers. They are 2 readonly sram saved in the same file but 
they are usualy set do diffrent adress(reg A, reg B). Next I have alu and 3 
sram which save data to adress chosen at first register(reg A). I toggle 
read/write pin from hight to low in order save. When I want to add the same 
number(reg B) another time the sram, where should be it, shows valute from 
reg A. When sram's disable pin gets pulse it refresh outputs and sram shows 
valute that it should show. I woudl ask if I can give you server adress. 
I'm not sure if configuration is completly done.

**Comment by jpfx1342** [comment]
Here, I'm going to try to describe your situation, tell me if I got it right. Here is your setup:
- You have 2 read-only SRAM chips (A) and (B), pointed to your "global" ram file. You modify their address inputs to read the memory.
- You have a third SRAM chip (C), also pointed at your "global" ram file, and setup for writing. You toggle it's write pin to do so.
- You have an ALU. It's internal operation is not important, but it reads from (A) and (B), and when done with an operation, it attempts to write to (C).

Here is your attempt to operate the circuit:
- SRAM chip (A) is set to read from address "1", (B) is set to "2", and (C) is set to "1"
- You trigger the ALU, it reads from (A) and (B), and writes to (C).
- When (C) is triggered to write, (A) should update it's output to reflect the new value of address "1", but it does not. (This would be the bug.)

**Comment by Kubuxu** [comment]
No. When C is triggered, A update but B have the same valute on output as A 
That is a bug.

**Comment by jpfx1342** [comment]
Why would the output of B change if A is set to a different address? Are you sure you're not getting some sort of crossover between the outputs of A and B? You're holding the readWrite pins of the SRAM chips high at all times, and only toggling them to false and back for a write? (Note that "readonly" chips have neither a readWrite pin, nor data pins.) Other than that, I'm probably going to have to know more about your setup to actually do anything.

**Comment by jpfx1342** [comment]
Another thing to consider is that the value the ALU puts in address "one" may simply have the same value as address "2". Have you ensured that your ALU is outputting the correct value? Have you tried different input values?

Note that the info wand ("/rctool") can be very helpful in debugging circuits. You may also find the "/rcdebug" command useful (although the info wand can fill its role). I would recommend enabling debugging for each of the SRAM chips, and trying to operate the circuit again.

http://eisental.github.com/RedstoneChips/howto.html#plugin_commands

**Comment by Kubuxu** [comment]
Propably I'll send IP of our Minecraft server. I'll be there tommorow at 
time that you sent your message. We found another chip with this bug. In 
bout cases there is sight, wool, second sight, and wool of the same colour.

**Comment by Kubuxu** [comment]
The adress is goldspeak.pl

You should spawn direcly bellow ALU.

**Comment by jpfx1342** [comment]
I'm not sure if I'll be able to get on today, it just sorta depends, but I got on yesterday and poked around (don't worry, I didn't touch anything).  I'm not sure exactly how your ALU is built, but it looks like your SRAM chips might be setup incorrectly. You have an SRAM chip attached to an input of each segment of your ALU. However, it looks like each of those SRAM chips is set to a separate memory-id. This means that each of those SRAM chips is going to access a different memory file.

As noted, this may be the intended setup, but if it is, it seems like a very roundabout way of getting the data to the ALU. Unless this is the intended behavior, each of those SRAM chips should be set to the same memory-id (something like "kubuxu-ram" or something).

But also as noted, I may just not understand your setup.

**Comment by Kubuxu** [comment]
Those chips which are set to another id are filters problem was with input srams. Those are dark green. I found another bug. I'm writing commit now.
