### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Kubuxu** [eisental/BasicCircuits#22]
Can you recompile this for me.

**Comment by eisental** [comment]
I will release a new version when I have the time.

**Comment by jpfx1342** [comment]
There is an unofficial build available in my repo, here: https://github.com/jpfx1342/RedstoneChips/downloads

Note that this build is not endorsed by eisential, and he may not support it's use. (i.e., any problems with this build are mine, not his.) In addition, it is built off of my fork, so it includes code not in eisential's repo. (Mainly repeater and sram improvements.)

For more details on the changes in my repo, see this pull request: https://github.com/eisental/BasicCircuits/pull/19

**Comment by Kubuxu** [comment]
I mostly need fixed the newest bug that I found because it destroy our
mechanize.

**Comment by jpfx1342** [comment]
The commit you're referring to is included in that build: https://github.com/jpfx1342/BasicCircuits/commits/master

EDIT: Updated the build to include a fix of mine: https://github.com/jpfx1342/BasicCircuits/commit/9d702a1fbf53fb39881e3c9694efcf453cb9818a
