### ISSUE TITLE
build error with 093a sources

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#7]
Hi Tal,

i'm getting  the following  with either 'mvn package' or 'mvn package install' (my maven system IS working for compiling RedStoneChips)

I haven't changed any of the source files. this is "out of the box" :)
Mike

D:\Maven\RedstoneChips093a>mvn --version
Apache Maven 3.0.3 (r1075438; 2011-02-28 12:31:09-0500)
Maven home: D:\Maven\apache-maven-3.0.3\bin..
Java version: 1.6.0_26, vendor: Sun Microsystems Inc.
Java home: d:\jdk\jre
Default locale: en_US, platform encoding: Cp1252
# OS name: "windows xp", version: "5.1", arch: "x86", family: "windows"

---

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.tal:BasicCircuits:jar:beta
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 20, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building BasicCircuits beta
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ BasicCircuits ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ BasicCircuits ---
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 44 source files to D:\Maven\BasicCircuits\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\terminal.java:[9,36] cannot find symbol
symbol  : class InterfaceBlock
location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[11,36] cannot find symbol
symbol  : class InterfaceBlock
location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\synth.java:[10,36] cannot find symbol
symbol  : class InterfaceBlock
location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\print.java:[16,36] cannot find symbol
symbol  : class InterfaceBlock
location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\terminal.java:[70,13] cannot find symbol
symbol  : class InterfaceBlock
location: class org.tal.basiccircuits.terminal
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[121,13] cannot find symbol
symbol  : class InterfaceBlock
location: class org.tal.basiccircuits.pixel
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[144,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[145,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[146,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[147,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[148,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[149,35] cannot find symbol
symbol  : method getLocation()
location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\sram.java:[313,24] cannot find symbol
symbol  : method pageMaker(org.bukkit.entity.Player,java.lang.String,java.lang.String,java.lang.String,org.bukkit.ChatColor,org.bukkit.ChatColor)
location: class org.tal.redstonechips.command.CommandUtils
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\synth.java:[114,17] cannot find symbol
symbol  : class InterfaceBlock
location: class org.tal.basiccircuits.synth
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\print.java:[285,13] cannot find symbol
symbol  : class InterfaceBlock
location: class org.tal.basiccircuits.print
[INFO] 15 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.922s
[INFO] Finished at: Thu Dec 22 05:29:17 EST 2011
[INFO] Final Memory: 6M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project BasicCircuits: Compilation failure: Compilation failure:
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\terminal.java:[9,36] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[11,36] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\synth.java:[10,36] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\print.java:[16,36] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: package org.tal.redstonechips.circuit
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\terminal.java:[70,13] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: class org.tal.basiccircuits.terminal
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\pixel.java:[121,13] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: class org.tal.basiccircuits.pixel
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[144,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[145,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[146,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[147,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[148,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\display.java:[149,35] cannot find symbol
[ERROR] symbol  : method getLocation()
[ERROR] location: class org.bukkit.Location
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\sram.java:[313,24] cannot find symbol
[ERROR] symbol  : method pageMaker(org.bukkit.entity.Player,java.lang.String,java.lang.String,java.lang.String,org.bukkit.ChatColor,org.bukkit.ChatColor)
[ERROR] location: class org.tal.redstonechips.command.CommandUtils
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\synth.java:[114,17] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: class org.tal.basiccircuits.synth
[ERROR] \Maven\BasicCircuits\src\main\java\org\tal\basiccircuits\print.java:[285,13] cannot find symbol
[ERROR] symbol  : class InterfaceBlock
[ERROR] location: class org.tal.basiccircuits.print
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by eisental** [comment]
Did you solve that? It was probably compiled against an older RedstoneChips version.

**Comment by mstram** [comment]
It's working.

I did a mvn package install on 093a which fixed it

Mike
