### ISSUE TITLE
/rctype dump (on sram) without args crashes bukkit

### ISSUE THREAD

**Issue by mstram** [eisental/BasicCircuits#9]
/rctype dump <enter>  causes bukkit (craftbukkit-1.0.1-R2-SNAPSHOT.jar) to go into an apparent loop ... memory use increases rapidly ... 

This happens regardless if the sram has been written to or not.  Or written with "/rctype <val>" or using the the input levers.

I also tested writing to sram, exiting m.c and stopping bukkit (at which point the ram file is apparently updated), restarting bukkit / m.c., still the same error on "/rctype dump <enter>"

Mike

**Comment by eisental** [comment]
Do you have the error message or did it just freeze?

**Comment by mstram** [comment]
TherNo error messages  in the bukkit console.

Client just gives "generic" "Read timed out"

On 12/25/11, Tal Eisenberg
reply@reply.github.com
wrote:

**Comment by mstram** [comment]
/rctype dump <enter> works in 092 ... so "something" must have changed :)

**Comment by mstram** [comment]
Hi Tal,

I started to look into that error, it seems the problem is not in the
sram.java file, as it appears to be almost identical to the 092
version.

What do you use for debugging tools ?

On another note, an interesting mod for "vanilla" minecraft :
http://www.minecraftforum.net/topic/892282-100-computercraft/

It's an embedded Lua "computer" on a block.

Pretty cool, but one of the major limitations compared to your system
is that it's not easy to use all 6 sides of the block, i.e. physically
"wiring it up" (although I was actually using a wireless mod).

He apparently has already had ~2,000 downloads in a few days !

Someone even started writing a "circuits" "templating" system .. heh
sound familiar ? I sent him a link to your site, he may / may not know
about your program.

Which leads me back to a brief discussion we had, on why you chose to
code for Bukkit vs
"vanilla" minecraft ?

I don't know a lot about either, but Bukkit plugins seem much cleaner
than dragging classes into the original minecraft.jar file.

Is that one of the reasons ?

Of course there's also quite a difference between a client-side or
server-side plugin mod (though not really noticeable ... if at all by
the player.

Do you know how many downloads approx you've had?

It might be worth thinking about porting the code to the standard
minecraft, as I think ?? (no idea
), that there might be more users who are using standard rather than Bukkit.

Or maybe not ;)

Happy Holidays.

Mike

**Comment by eisental** [comment]
Could you send a schematic of your sram? I didn't run into this bug. /rctype works fine for me. Does it happen with any sram or did you try just one?

I didn't bother getting into client mod programming. It seemed to be too much trouble for big projects like redstonechips so I was waiting for official mod support. That of course didn't happen. 
Right now spout seems like it would be the best option for having one plugin for both singleplayer and multiplayer but there's still a long way to go... 

This computer looks very cool indeed :) A programmable chip is one of the oldest items on the todo list but I always run into problems trying to add a script interpreter to a plugin.

**Comment by eisental** [comment]
I'm not running any mods and it works also with the spoutcraft client.
Using last recommended bukkit build (will check it out with the latest
later).
Did you try building the sram differently? maybe it has something to do
with the structure, although I doubt it.

Personally I'm more interested in ruby scripting. I never tried Lua.
Embedding is not the problem though. Adding jar libraries to craftbukkit is
a pain.

On Tue, Dec 27, 2011 at 6:25 PM, Mike Stramba <
reply@reply.github.com

**Comment by eisental** [comment]
Can you make another issue for shifting right? 
I don't think there's enough space for multiple formatting arguments in print but I'll check it out.
There are still a lot of features I want to add to RC, but I don't have enough time to code all of them.

**Comment by eisental** [comment]
It's not a problem to compile with jruby lib using Maven, but you need to add the jruby.jar to the java classpath somehow to make craftbukkit load it. Ideally I could just throw it into the plugins folder but this causes an error when bukkit starts-up. I'm sure there are other bukkit plugins that use external libraries but I haven't found any solution for that yet. This probably needs some messing around with custom class loaders.

**Comment by eisental** [comment]
I think I found everything I was looking for :) 
https://github.com/Zeerix/RubyBukkit/

**Comment by mstram** [comment]
I think the problem is a "time out"  + my computer may not be fast enough.

I just tried an 8bit addr ram (256 bytes), and it works ok, as did a 9bit (512), but a 16 bit causes the hang /timeout / disconnect.

I never let it run "long enough" to see if the system recovers ... I'll do that next

**Comment by eisental** [comment]
Ok, I finally managed to reproduce this bug. I'll see if I can fix it later.

On Fri, Dec 30, 2011 at 6:53 PM, Mike Stramba <
reply@reply.github.com

**Comment by eisental** [comment]
Fixed!

https://github.com/eisental/RedstoneChips/commit/d708e5bda93a20260e8590d540cdc19e604e9f2c

https://github.com/eisental/BasicCircuits/commit/483c71f59c73d0aa6c3e43d6d5bc69401179b72b
